# =================================================
# APPLICATION
# =================================================
spring.application.name=peace
server.port=8082

# =================================================
# PROFILES SPRING (dev = H2, prod = PostgreSQL)
# =================================================
# Pour utiliser H2 en local : spring.profiles.active=dev
# Pour utiliser PostgreSQL en prod : spring.profiles.active=prod
#spring.profiles.active=dev

# =================================================
# H2 PERSISTANTE (DEV)
# =================================================
# H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Base H2 persistante sur disque (créera ./data/smartv2.mv.db)
#spring.datasource.url=jdbc:h2:file:./data/smartv2
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

#Exécuter data.sql seulement si la table est vide (option par défaut)
#spring.sql.init.mode=always
#spring.sql.init.platform=h2
#server.error.include-message=always


# =================================================
# POSTGRESQL (PROD)
# =================================================
spring.datasource.url=jdbc:postgresql://dpg-d64uldnpm1nc738vospg-a.oregon-postgres.render.com:5432/database_smartv2_26z1?ssl=true&sslmode=require
spring.datasource.username=ccoundbd_userv2
spring.datasource.password=JsUtqG50HQJ950NDpBv9Q0ISrEOAk1nw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=never

# =========================
# FALLBACK DATASOURCE (H2)
# MODE=PostgreSQL pour compatibilité SQL
# =========================
#app.datasource.fallback.url=jdbc:h2:mem:peace;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
app.datasource.fallback.url=jdbc:h2:file:./data/peace;MODE=PostgreSQL
app.datasource.fallback.username=sa
app.datasource.fallback.password=
app.datasource.fallback.driver-class-name=org.h2.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# =================================================
# JPA / HIBERNATE
# =================================================
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG


# =================================================
# FILE UPLOAD
# =================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=3000MB
spring.servlet.multipart.max-request-size=5000MB

# =================================================
# JWT SECURITY
# =================================================
bezkoder.app.jwtSecret======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000

# =================================================
# MAIL (SMTP GMAIL)
# =================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kingproduct45@gmail.com
spring.mail.password=xovb nmbg qmmx wgwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# =================================================
# TASK SCHEDULING
# =================================================
spring.task.scheduling.pool.size=5
